import json
import subprocess
import sys

import pytest

from deck_builder import __version__
from deck_builder.cli import main
from deck_builder.errors import CODES, EXIT_ENV, EXIT_OK


def run(capsys, *argv):
    code = main(list(argv))
    out = capsys.readouterr()
    return code, out.out, out.err


def test_version(capsys):
    with pytest.raises(SystemExit) as e:
        main(["--version"])
    assert e.value.code == 0
    assert __version__ in capsys.readouterr().out


def test_no_command_prints_help_and_exits_2(capsys):
    code, out, _ = run(capsys)
    assert code == EXIT_ENV
    assert "<command>" in out


def test_every_issue_code_is_exercised_by_a_test():
    """R-9.1: each code appears in at least one test file other than this one."""
    from pathlib import Path

    tests = Path(__file__).resolve().parents[1]
    text = "".join(p.read_text() for p in tests.rglob("test_*.py") if p.name != "test_cli.py")
    untested = [c for c in CODES if c not in text]
    assert untested == [], f"no test mentions: {untested}"


def test_committed_issue_codes_doc_matches_the_engine():
    """R-9.1: docs/issue-codes.md is generated by `deck-builder docs codes`."""
    from pathlib import Path

    from deck_builder.docs import codes_markdown

    doc = Path(__file__).resolve().parents[2] / "docs" / "issue-codes.md"
    assert doc.read_text() == codes_markdown(), "regenerate: deck-builder docs codes > docs/issue-codes.md"


def test_docs_lists_topics(capsys):
    code, out, _ = run(capsys, "docs", "--json")
    assert code == EXIT_OK
    topics = json.loads(out)["topics"]
    assert {"codes", "deck-md", "workflow"} <= set(topics)


def test_docs_codes_covers_every_code(capsys):
    code, out, _ = run(capsys, "docs", "codes")
    assert code == EXIT_OK
    for c in CODES:
        assert f"`{c}`" in out


def test_docs_unknown_topic_exits_2(capsys):
    code, _, err = run(capsys, "docs", "nope")
    assert code == EXIT_ENV
    assert "unknown docs topic" in err


def test_explain_is_case_insensitive(capsys):
    code, out, _ = run(capsys, "explain", "budget_chars", "--json")
    assert code == EXIT_OK
    assert json.loads(out)["code"] == "BUDGET_CHARS"


def test_explain_unknown_code_exits_2(capsys):
    code, _, _ = run(capsys, "explain", "NOPE")
    assert code == EXIT_ENV


def test_installed_entry_point_runs():
    r = subprocess.run([sys.executable, "-m", "deck_builder", "--version"], capture_output=True, text=True)
    assert r.returncode == 0
    assert __version__ in r.stdout
